name: Auto-Merge Main to Staging

on:
    push:
        branches:
            - main

jobs:
    automated_merge:
        if: startsWith(github.event.head_commit.message, 'Automated:')
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master

            - name: Automated merge (staging -> main)
              uses: devmasx/merge-branch@master
              with:
                  type: now
                  from_branch: main
                  target_branch: staging
                  message: Automated merge from main
                  github_token: ${{ secrets.GITHUB_TOKEN }}

            - name: POST call datagovmy staging
              uses: fjogeleit/http-request-action@v1
              with:
                  url: "https://staging.datagovmy.app/update/"
                  method: "POST"
                  customHeaders: '{"Authorization": "${{ secrets.WORKFLOW_TOKEN_STAGING }}"}'
                  timeout: 30000

            - name: POST call openapi staging
              uses: fjogeleit/http-request-action@v1
              with:
                  url: "https://staging.datagovmy.dev/data-catalogue/update/"
                  method: "POST"
                  customHeaders: '{"Authorization": "${{ secrets.DATA_CATALOGUE_TOKEN_STAGING }}"}'
                  timeout: 30000
